name: canlifal_mobile
description: Native Flutter social live streaming app preview.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.9.2
  firebase_auth: ^6.5.1
  firebase_core: ^4.9.0
  firebase_messaging: ^16.2.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.1
  flutter_secure_storage: ^10.2.0
  go_router: ^17.2.3
  http: ^1.6.0
  intl: ^0.20.2
  shared_preferences: ^2.5.5
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/brand/vivalive_logo.png
