import type { SiteAnimationRecord } from "./siteAnimationStore";

/** Mobil seed katalogu ile hizalı başlangıç verisi. */
export const SITE_ANIMATION_SEED: SiteAnimationRecord[] = [
  {
    id: "anim_entrance_normal",
    name: "Normal Giriş — Hoş geldin",
    category: "entrance",
    membership: "normal",
    animationType: "native",
    durationMs: 2500,
    priority: 50,
    rarity: "common",
    context: "voice_room",
    anchor: "TOP_LEFT",
    scale: 1,
    cooldownMs: 0,
    isActive: true,
    description: "Mavi halka, sade banner — 2.5 sn",
  },
  {
    id: "anim_entrance_gold_crown",
    name: "Golden Crown — Gold Üye Girişi",
    category: "entrance",
    membership: "gold",
    animationType: "lottie",
    assetUrl: "assets/gifts/lottie/crown.json",
    durationMs: 3000,
    priority: 70,
    rarity: "common",
    context: "voice_room",
    anchor: "TOP_LEFT",
    scale: 1,
    cooldownMs: 0,
    isActive: true,
    description: "Altın taç + glow + VIP rozeti",
    previewMp4Key: "gold_uye_girisi.mp4",
  },
  {
    id: "anim_entrance_premium_star",
    name: "Premium Star — Premium Üye Girişi",
    category: "entrance",
    membership: "premium",
    animationType: "lottie",
    assetUrl: "assets/gifts/lottie/star.json",
    durationMs: 4000,
    priority: 80,
    rarity: "common",
    context: "voice_room",
    anchor: "TOP_LEFT",
    scale: 1,
    cooldownMs: 0,
    isActive: true,
    description: "Mor yıldız + kanat efekti",
    previewMp4Key: "premium_uye_girisi.mp4",
  },
  {
    id: "anim_entrance_diamond_burst",
    name: "Diamond Burst — Diamond Üye Girişi",
    category: "entrance",
    membership: "diamond",
    animationType: "lottie",
    assetUrl: "assets/gifts/lottie/crown.json",
    durationMs: 4000,
    priority: 90,
    rarity: "epic",
    context: "voice_room",
    anchor: "TOP_LEFT",
    scale: 1,
    cooldownMs: 0,
    isActive: true,
    description: "Mavi kristal patlaması",
    previewMp4Key: "diamond_uye_girisi.mp4",
  },
  {
    id: "anim_entrance_vip_galaxy",
    name: "Galaxy VIP — VIP Üye Girişi",
    category: "entrance",
    membership: "vip",
    animationType: "lottie",
    assetUrl: "assets/gifts/lottie/rose.json",
    durationMs: 4000,
    priority: 65,
    rarity: "rare",
    context: "voice_room",
    anchor: "TOP_LEFT",
    scale: 1,
    cooldownMs: 0,
    isActive: true,
    description: "Mor galaksi halkası",
  },
  {
    id: "anim_entrance_svip_emperor",
    name: "Dragon Emperor — SVIP Girişi",
    category: "entrance",
    membership: "svip",
    animationType: "lottie",
    assetUrl: "assets/gifts/lottie/crown.json",
    durationMs: 4000,
    priority: 85,
    rarity: "legendary",
    context: "voice_room",
    anchor: "TOP_LEFT",
    scale: 1,
    cooldownMs: 0,
    isActive: true,
    description: "EMPEROR rozeti + altın ışın",
  },
  {
    id: "anim_entrance_admin_galaxy",
    name: "Admin Galaxy — Site Admin Girişi",
    category: "entrance",
    membership: "admin",
    animationType: "lottie",
    assetUrl: "assets/gifts/lottie/car.json",
    durationMs: 4000,
    priority: 100,
    rarity: "legendary",
    context: "voice_room",
    anchor: "TOP_LEFT",
    scale: 1,
    cooldownMs: 0,
    isActive: true,
    description: "ADMIN rozeti + mor kanat + galaxy",
    previewMp4Key: "admin_girisi.mp4",
  },
  {
    id: "anim_exit_normal",
    name: "Normal Çıkış — Güle güle",
    category: "exit",
    membership: "normal",
    animationType: "native",
    durationMs: 2000,
    priority: 30,
    rarity: "common",
    context: "voice_room",
    anchor: "TOP_LEFT",
    scale: 1,
    cooldownMs: 0,
    isActive: true,
  },
  {
    id: "anim_exit_gold",
    name: "Gold Çıkış — Tekrar bekleriz",
    category: "exit",
    membership: "gold",
    animationType: "lottie",
    assetUrl: "assets/gifts/lottie/heart.json",
    durationMs: 2000,
    priority: 35,
    rarity: "common",
    context: "voice_room",
    anchor: "TOP_LEFT",
    scale: 1,
    cooldownMs: 0,
    isActive: true,
  },
  {
    id: "anim_exit_premium",
    name: "Premium Çıkış — Yine bekleriz",
    category: "exit",
    membership: "premium",
    animationType: "lottie",
    assetUrl: "assets/gifts/lottie/star.json",
    durationMs: 3000,
    priority: 36,
    rarity: "common",
    context: "voice_room",
    anchor: "TOP_LEFT",
    scale: 1,
    cooldownMs: 0,
    isActive: true,
  },
  {
    id: "anim_exit_diamond",
    name: "Diamond Çıkış — Işıkla kal",
    category: "exit",
    membership: "diamond",
    animationType: "lottie",
    assetUrl: "assets/gifts/lottie/crown.json",
    durationMs: 3000,
    priority: 37,
    rarity: "common",
    context: "voice_room",
    anchor: "TOP_LEFT",
    scale: 1,
    cooldownMs: 0,
    isActive: true,
  },
  {
    id: "anim_exit_vip",
    name: "VIP Çıkış — Kral geri dönecek",
    category: "exit",
    membership: "vip",
    animationType: "lottie",
    assetUrl: "assets/gifts/lottie/rose.json",
    durationMs: 3000,
    priority: 38,
    rarity: "common",
    context: "voice_room",
    anchor: "TOP_LEFT",
    scale: 1,
    cooldownMs: 0,
    isActive: true,
  },
  {
    id: "anim_exit_admin",
    name: "Admin Çıkış — Sistemden ayrıldı",
    category: "exit",
    membership: "admin",
    animationType: "native",
    durationMs: 3000,
    priority: 40,
    rarity: "common",
    context: "voice_room",
    anchor: "TOP_LEFT",
    scale: 1,
    cooldownMs: 0,
    isActive: true,
  },
  {
    id: "anim_mic_on",
    name: "Mikrofon Açma",
    category: "mic",
    membership: "all",
    animationType: "lottie",
    assetUrl: "assets/gifts/lottie/star.json",
    durationMs: 2000,
    priority: 40,
    rarity: "common",
    context: "voice_room",
    anchor: "SEAT",
    scale: 1,
    cooldownMs: 0,
    isActive: true,
    previewMp4Key: "mikrofon_acma.mp4",
  },
  {
    id: "anim_mic_off",
    name: "Mikrofon Kapatma",
    category: "mic",
    membership: "all",
    animationType: "native",
    durationMs: 2000,
    priority: 40,
    rarity: "common",
    context: "voice_room",
    anchor: "SEAT",
    scale: 1,
    cooldownMs: 0,
    isActive: true,
    previewMp4Key: "mikrofon_kapatma.mp4",
  },
  {
    id: "anim_host_seat_crown",
    name: "Host Koltuğu — Taç & Parıltı",
    category: "host",
    membership: "host",
    animationType: "lottie",
    assetUrl: "assets/gifts/lottie/crown.json",
    durationMs: 3200,
    priority: 95,
    rarity: "legendary",
    context: "voice_room",
    anchor: "SEAT",
    scale: 1,
    cooldownMs: 0,
    isActive: true,
    previewMp4Key: "host_koltugu.mp4",
  },
  {
    id: "anim_transition_seat_change",
    name: "Koltuk Değiştirme",
    category: "transition",
    membership: "all",
    animationType: "native",
    durationMs: 2000,
    priority: 45,
    rarity: "common",
    context: "voice_room",
    anchor: "SEAT",
    scale: 1,
    cooldownMs: 0,
    isActive: true,
  },
  {
    id: "anim_seat_gold",
    name: "Gold Koltuk — Altın Halka",
    category: "seat",
    membership: "gold",
    animationType: "lottie",
    assetUrl: "assets/gifts/lottie/heart.json",
    durationMs: 3000,
    priority: 70,
    rarity: "common",
    context: "voice_room",
    anchor: "SEAT",
    scale: 1,
    cooldownMs: 0,
    isActive: true,
  },
  {
    id: "anim_seat_diamond",
    name: "Diamond Koltuk — Kristal",
    category: "seat",
    membership: "diamond",
    animationType: "lottie",
    assetUrl: "assets/gifts/lottie/crown.json",
    durationMs: 3000,
    priority: 90,
    rarity: "epic",
    context: "voice_room",
    anchor: "SEAT",
    scale: 1,
    cooldownMs: 0,
    isActive: true,
  },
];

export const SITE_ANIMATION_DEFAULTS: Record<string, string> = {
  normal: "anim_entrance_normal",
  gold: "anim_entrance_gold_crown",
  premium: "anim_entrance_premium_star",
  diamond: "anim_entrance_diamond_burst",
  vip: "anim_entrance_vip_galaxy",
  svip: "anim_entrance_svip_emperor",
  admin: "anim_entrance_admin_galaxy",
  host: "anim_host_seat_crown",
};
