import type { SiteAnimationRecord } from "./siteAnimationStore";

const base = (
  item: Partial<SiteAnimationRecord> &
    Pick<SiteAnimationRecord, "id" | "name" | "category" | "membership">,
): SiteAnimationRecord => ({
  animationType: "native",
  durationMs: 3000,
  priority: 50,
  rarity: "common",
  context: "voice_room",
  anchor: "TOP_LEFT",
  scale: 1,
  cooldownMs: 0,
  isActive: true,
  ...item,
});

/** Mobil admin seed katalogu ile hizalı tam liste. */
export const SITE_ANIMATION_SEED: SiteAnimationRecord[] = [
  base({
    id: "anim_entrance_normal",
    name: "Normal Giriş — Hoş geldin",
    category: "entrance",
    membership: "normal",
    durationMs: 2500,
    description: "Mavi halka, sade banner — 2.5 sn",
  }),
  base({
    id: "anim_entrance_gold_crown",
    name: "Golden Crown — Gold Üye Girişi",
    category: "entrance",
    membership: "gold",
    animationType: "lottie",
    assetUrl: "assets/gifts/lottie/crown.json",
    durationMs: 3000,
    priority: 70,
    cooldownMs: 8000,
    soundUrl: "https://cdn.canlifal.com/animations/sounds/anim_entrance_gold_crown.mp3",
    previewMp4Key: "gold_uye_girisi.mp4",
    description: "Altın taç + glow + VIP rozeti",
  }),
  base({
    id: "anim_entrance_premium_star",
    name: "Premium Star — Premium Üye Girişi",
    category: "entrance",
    membership: "premium",
    animationType: "lottie",
    assetUrl: "assets/gifts/lottie/star.json",
    durationMs: 4000,
    priority: 80,
    previewMp4Key: "premium_uye_girisi.mp4",
  }),
  base({
    id: "anim_entrance_diamond_burst",
    name: "Diamond Burst — Diamond Üye Girişi",
    category: "entrance",
    membership: "diamond",
    animationType: "lottie",
    assetUrl: "assets/gifts/lottie/crown.json",
    durationMs: 4000,
    priority: 90,
    rarity: "epic",
    previewMp4Key: "diamond_uye_girisi.mp4",
  }),
  base({
    id: "anim_entrance_vip_galaxy",
    name: "Galaxy VIP — VIP Üye Girişi",
    category: "entrance",
    membership: "vip",
    animationType: "lottie",
    assetUrl: "assets/gifts/lottie/rose.json",
    durationMs: 4000,
    priority: 65,
    rarity: "rare",
  }),
  base({
    id: "anim_entrance_svip_emperor",
    name: "Dragon Emperor — SVIP Girişi",
    category: "entrance",
    membership: "svip",
    animationType: "lottie",
    assetUrl: "assets/gifts/lottie/crown.json",
    durationMs: 4000,
    priority: 85,
    rarity: "legendary",
  }),
  base({
    id: "anim_entrance_admin_galaxy",
    name: "Admin Galaxy — Site Admin Girişi",
    category: "entrance",
    membership: "admin",
    animationType: "lottie",
    assetUrl: "assets/gifts/lottie/car.json",
    durationMs: 4000,
    priority: 110,
    rarity: "legendary",
    previewMp4Key: "admin_girisi.mp4",
  }),
  base({
    id: "anim_entrance_golden_spotlight",
    name: "Golden Spotlight — Platinum Girişi",
    category: "entrance",
    membership: "premium",
    animationType: "lottie",
    assetUrl: "assets/gifts/lottie/star.json",
    durationMs: 3000,
    priority: 40,
  }),
  base({
    id: "anim_entrance_royal_gate",
    name: "Royal Gate — VIP Girişi",
    category: "entrance",
    membership: "vip",
    animationType: "lottie",
    assetUrl: "assets/gifts/lottie/crown.json",
    durationMs: 3500,
    priority: 80,
    rarity: "epic",
  }),
  base({
    id: "anim_entrance_golden_dust",
    name: "Golden Dust — Minimal Giriş",
    category: "entrance",
    membership: "gold",
    animationType: "lottie",
    assetUrl: "assets/gifts/lottie/heart.json",
    durationMs: 2500,
    priority: 30,
  }),
  base({
    id: "anim_entrance_fire_crown",
    name: "Fire Crown — Alev Taç",
    category: "entrance",
    membership: "gold",
    animationType: "lottie",
    assetUrl: "assets/gifts/lottie/crown.json",
    durationMs: 2200,
    priority: 35,
    rarity: "rare",
  }),
  base({
    id: "anim_entrance_angel_wings",
    name: "Angel Wings — Premium Kanat",
    category: "entrance",
    membership: "premium",
    animationType: "lottie",
    assetUrl: "assets/gifts/lottie/star.json",
    durationMs: 3200,
    priority: 42,
    rarity: "rare",
  }),
  base({
    id: "anim_entrance_lightning_diamond",
    name: "Lightning Diamond — Elektrik Giriş",
    category: "entrance",
    membership: "diamond",
    animationType: "lottie",
    assetUrl: "assets/gifts/lottie/crown.json",
    durationMs: 2800,
    priority: 60,
    rarity: "epic",
  }),
  base({
    id: "anim_entrance_royal_star",
    name: "Royal Star — Yıldız Halkası",
    category: "entrance",
    membership: "premium",
    animationType: "lottie",
    assetUrl: "assets/gifts/lottie/star.json",
    durationMs: 3000,
    priority: 41,
  }),
  base({
    id: "anim_entrance_cosmic_portal",
    name: "Cosmic Portal — Mistik Giriş",
    category: "entrance",
    membership: "vip",
    animationType: "lottie",
    assetUrl: "assets/gifts/lottie/rose.json",
    durationMs: 3500,
    priority: 78,
    rarity: "legendary",
  }),
  base({ id: "anim_frame_gold_crown", name: "Gold Crown Frame", category: "profileFrame", membership: "gold", animationType: "lottie", assetUrl: "assets/gifts/lottie/crown.json", durationMs: 0, priority: 30, context: "profile" }),
  base({ id: "anim_frame_diamond", name: "Diamond Frame", category: "profileFrame", membership: "diamond", animationType: "lottie", assetUrl: "assets/gifts/lottie/crown.json", durationMs: 0, priority: 60, context: "profile", rarity: "epic" }),
  base({ id: "anim_frame_royal", name: "Royal Frame", category: "profileFrame", membership: "vip", animationType: "lottie", assetUrl: "assets/gifts/lottie/crown.json", durationMs: 0, priority: 80, context: "profile" }),
  base({ id: "anim_frame_galaxy", name: "Galaxy Frame", category: "profileFrame", membership: "svip", animationType: "lottie", assetUrl: "assets/gifts/lottie/crown.json", durationMs: 0, priority: 90, context: "profile", rarity: "rare" }),
  base({ id: "anim_frame_fire", name: "Fire Frame", category: "profileFrame", membership: "gold", animationType: "lottie", assetUrl: "assets/gifts/lottie/crown.json", durationMs: 0, priority: 32, context: "profile", rarity: "rare" }),
  base({ id: "anim_frame_angel", name: "Angel Frame", category: "profileFrame", membership: "premium", animationType: "lottie", assetUrl: "assets/gifts/lottie/crown.json", durationMs: 0, priority: 42, context: "profile" }),
  base({ id: "anim_frame_lightning", name: "Lightning Frame", category: "profileFrame", membership: "diamond", animationType: "lottie", assetUrl: "assets/gifts/lottie/crown.json", durationMs: 0, priority: 62, context: "profile", rarity: "epic" }),
  base({ id: "anim_frame_neon", name: "Neon Frame", category: "profileFrame", membership: "vip", animationType: "lottie", assetUrl: "assets/gifts/lottie/crown.json", durationMs: 0, priority: 78, context: "profile" }),
  base({ id: "anim_frame_cosmic", name: "Cosmic Frame", category: "profileFrame", membership: "vip", animationType: "lottie", assetUrl: "assets/gifts/lottie/crown.json", durationMs: 0, priority: 79, context: "profile", rarity: "legendary" }),
  base({ id: "anim_frame_dragon", name: "Dragon Frame", category: "profileFrame", membership: "svip", animationType: "lottie", assetUrl: "assets/gifts/lottie/crown.json", durationMs: 0, priority: 92, context: "profile", rarity: "legendary" }),
  base({ id: "anim_frame_star", name: "Star Frame", category: "profileFrame", membership: "premium", animationType: "lottie", assetUrl: "assets/gifts/lottie/crown.json", durationMs: 0, priority: 41, context: "profile" }),
  base({ id: "anim_frame_emperor", name: "Emperor Frame", category: "profileFrame", membership: "svip", animationType: "lottie", assetUrl: "assets/gifts/lottie/crown.json", durationMs: 0, priority: 100, context: "profile", rarity: "legendary" }),
  base({ id: "anim_frame_crystal", name: "Crystal Frame", category: "profileFrame", membership: "diamond", animationType: "native", durationMs: 0, priority: 64, context: "profile", rarity: "epic" }),
  base({ id: "anim_frame_admin", name: "Admin Frame", category: "profileFrame", membership: "admin", animationType: "native", durationMs: 0, priority: 105, context: "profile", rarity: "legendary" }),
  base({ id: "anim_avatar_gold_glow", name: "Gold Glow", category: "avatarEffect", membership: "gold", durationMs: 0, context: "profile" }),
  base({ id: "anim_avatar_purple_glow", name: "Purple Glow", category: "avatarEffect", membership: "premium", durationMs: 0, context: "profile" }),
  base({ id: "anim_avatar_diamond_glow", name: "Diamond Glow", category: "avatarEffect", membership: "diamond", durationMs: 0, context: "profile" }),
  base({ id: "anim_avatar_galaxy_aura", name: "Galaxy Aura", category: "avatarEffect", membership: "svip", durationMs: 0, context: "profile" }),
  base({ id: "anim_avatar_fire_aura", name: "Fire Aura", category: "avatarEffect", membership: "gold", durationMs: 0, context: "profile" }),
  base({ id: "anim_avatar_lightning_aura", name: "Lightning Aura", category: "avatarEffect", membership: "diamond", durationMs: 0, context: "profile" }),
  base({ id: "anim_avatar_star_particle", name: "Star Particle", category: "avatarEffect", membership: "premium", durationMs: 0, context: "profile" }),
  base({ id: "anim_avatar_royal_aura", name: "Royal Aura", category: "avatarEffect", membership: "vip", durationMs: 0, context: "profile" }),
  base({ id: "anim_gift_gold_burst", name: "Gold Gift Burst", category: "gift", membership: "gold", animationType: "lottie", assetUrl: "assets/gifts/lottie/crown.json", durationMs: 2800, priority: 65, anchor: "TOP_CENTER", context: "gift" }),
  base({ id: "anim_gift_diamond_storm", name: "Diamond Gift Storm", category: "gift", membership: "diamond", animationType: "lottie", assetUrl: "assets/gifts/lottie/crown.json", durationMs: 2800, priority: 80, anchor: "TOP_CENTER", context: "gift", rarity: "epic" }),
  base({ id: "anim_gift_vip_royal", name: "VIP Royal Gift", category: "gift", membership: "vip", animationType: "lottie", assetUrl: "assets/gifts/lottie/rose.json", durationMs: 3000, priority: 85, anchor: "TOP_CENTER", context: "gift", rarity: "rare" }),
  base({ id: "anim_gift_svip_galaxy", name: "SVIP Galaxy Gift", category: "gift", membership: "svip", animationType: "lottie", assetUrl: "assets/gifts/lottie/star.json", durationMs: 3200, priority: 95, anchor: "TOP_CENTER", context: "gift", rarity: "legendary" }),
  base({ id: "anim_exit_normal", name: "Normal Çıkış — Güle güle", category: "exit", membership: "normal", durationMs: 2000, priority: 30 }),
  base({ id: "anim_exit_gold", name: "Gold Çıkış — Tekrar bekleriz", category: "exit", membership: "gold", animationType: "lottie", assetUrl: "assets/gifts/lottie/heart.json", durationMs: 2000, priority: 35, soundUrl: "https://cdn.canlifal.com/animations/sounds/anim_exit_gold.mp3" }),
  base({ id: "anim_exit_premium", name: "Premium Çıkış — Yine bekleriz", category: "exit", membership: "premium", animationType: "lottie", assetUrl: "assets/gifts/lottie/star.json", durationMs: 3000, priority: 36 }),
  base({ id: "anim_exit_diamond", name: "Diamond Çıkış — Işıkla kal", category: "exit", membership: "diamond", animationType: "lottie", assetUrl: "assets/gifts/lottie/crown.json", durationMs: 3000, priority: 37, soundUrl: "https://cdn.canlifal.com/animations/sounds/anim_exit_diamond.mp3" }),
  base({ id: "anim_exit_vip", name: "VIP Çıkış — Kral geri dönecek", category: "exit", membership: "vip", animationType: "lottie", assetUrl: "assets/gifts/lottie/rose.json", durationMs: 3000, priority: 38, soundUrl: "https://cdn.canlifal.com/animations/sounds/anim_exit_vip.mp3" }),
  base({ id: "anim_exit_svip", name: "SVIP Çıkış — İmparator yakında", category: "exit", membership: "svip", durationMs: 3000, priority: 39 }),
  base({ id: "anim_exit_admin", name: "Admin Çıkış — Sistemden ayrıldı", category: "exit", membership: "admin", durationMs: 3000, priority: 40 }),
  base({ id: "anim_transition_seat_change", name: "Koltuk Değiştirme", category: "transition", membership: "all", durationMs: 2000, priority: 45, anchor: "SEAT" }),
  base({ id: "anim_transition_stage_up", name: "Sahneye Geçiş", category: "transition", membership: "all", durationMs: 3000, priority: 44 }),
  base({ id: "anim_transition_host_handover", name: "Host Devir Teslimi", category: "transition", membership: "host", durationMs: 4000, priority: 95 }),
  base({ id: "anim_seat_normal", name: "Normal Koltuk — Sade Işık Halesi", category: "seat", membership: "normal", durationMs: 3000, priority: 50, anchor: "SEAT" }),
  base({ id: "anim_seat_gold", name: "Gold Koltuk — Altın Halka", category: "seat", membership: "gold", animationType: "lottie", assetUrl: "assets/gifts/lottie/heart.json", durationMs: 3000, priority: 70, anchor: "SEAT" }),
  base({ id: "anim_seat_premium", name: "Premium Koltuk — Mor Yıldız", category: "seat", membership: "premium", animationType: "lottie", assetUrl: "assets/gifts/lottie/star.json", durationMs: 3000, priority: 80, anchor: "SEAT" }),
  base({ id: "anim_seat_diamond", name: "Diamond Koltuk — Kristal", category: "seat", membership: "diamond", animationType: "lottie", assetUrl: "assets/gifts/lottie/crown.json", durationMs: 3000, priority: 90, anchor: "SEAT", rarity: "epic" }),
  base({ id: "anim_seat_vip", name: "VIP Koltuk — Kanat & Alev", category: "seat", membership: "vip", animationType: "lottie", assetUrl: "assets/gifts/lottie/rose.json", durationMs: 3000, priority: 65, anchor: "SEAT", rarity: "rare" }),
  base({ id: "anim_seat_svip", name: "SVIP Koltuk — Kraliyet", category: "seat", membership: "svip", animationType: "lottie", assetUrl: "assets/gifts/lottie/crown.json", durationMs: 3000, priority: 85, anchor: "SEAT", rarity: "legendary" }),
  base({ id: "anim_seat_admin", name: "Admin Koltuk — Taç", category: "seat", membership: "admin", animationType: "lottie", assetUrl: "assets/gifts/lottie/crown.json", durationMs: 3000, priority: 100, anchor: "SEAT" }),
  base({ id: "anim_room_gift_rain", name: "Hediye Yağmuru", category: "roomWide", membership: "all", durationMs: 5000, priority: 60 }),
  base({ id: "anim_room_star_rain", name: "Yıldız Yağmuru", category: "roomWide", membership: "all", animationType: "lottie", assetUrl: "assets/gifts/lottie/star.json", durationMs: 5000, priority: 58 }),
  base({ id: "anim_room_diamond_storm", name: "Diamond Fırtınası", category: "roomWide", membership: "diamond", animationType: "lottie", assetUrl: "assets/gifts/lottie/crown.json", durationMs: 6000, priority: 75 }),
  base({ id: "anim_room_love", name: "Aşk Efekti", category: "roomWide", membership: "all", animationType: "lottie", assetUrl: "assets/gifts/lottie/heart.json", durationMs: 5000, priority: 55 }),
  base({ id: "anim_room_bravo", name: "Tebrik — BRAVO", category: "roomWide", membership: "all", durationMs: 5000, priority: 62 }),
  base({ id: "anim_room_level_up", name: "Seviye Atladı", category: "roomWide", membership: "all", durationMs: 4000, priority: 63 }),
  base({ id: "anim_mic_on", name: "Mikrofon Açma", category: "mic", membership: "all", animationType: "lottie", assetUrl: "assets/gifts/lottie/star.json", durationMs: 2000, priority: 40, anchor: "SEAT", previewMp4Key: "mikrofon_acma.mp4" }),
  base({ id: "anim_mic_off", name: "Mikrofon Kapatma", category: "mic", membership: "all", durationMs: 2000, priority: 40, anchor: "SEAT", previewMp4Key: "mikrofon_kapatma.mp4" }),
  base({ id: "anim_host_seat_crown", name: "Host Koltuğu — Taç & Parıltı", category: "host", membership: "host", animationType: "lottie", assetUrl: "assets/gifts/lottie/crown.json", durationMs: 3200, priority: 95, anchor: "SEAT", previewMp4Key: "host_koltugu.mp4" }),
];

export const SITE_ANIMATION_DEFAULTS: Record<string, string> = {
  normal: "anim_entrance_normal",
  gold: "anim_entrance_gold_crown",
  premium: "anim_entrance_golden_spotlight",
  diamond: "anim_entrance_diamond_burst",
  vip: "anim_entrance_royal_gate",
  svip: "anim_entrance_vip_galaxy",
  admin: "anim_entrance_admin_galaxy",
  host: "anim_host_seat_crown",
};

export const SITE_ANIMATION_EXIT_DEFAULTS: Record<string, string> = {
  normal: "anim_exit_normal",
  gold: "anim_exit_gold",
  premium: "anim_exit_premium",
  diamond: "anim_exit_diamond",
  vip: "anim_exit_vip",
  svip: "anim_exit_svip",
  admin: "anim_exit_admin",
  host: "anim_exit_admin",
};
