#!/usr/bin/env bash
# google-services.json → mobile/lib/core/firebase/firebase_options_generated.dart

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
JSON="$ROOT/mobile/android/app/google-services.json"
OUT="$ROOT/mobile/lib/core/firebase/firebase_options_generated.dart"

if [[ ! -f "$JSON" ]]; then
  echo "generate-firebase-options: $JSON yok, atlanıyor"
  exit 0
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "generate-firebase-options: jq gerekli (apt install jq)"
  exit 1
fi

if head -c 1 "$JSON" | grep -qv '{'; then
  echo "generate-firebase-options: geçersiz JSON (HTML olabilir)"
  exit 1
fi

PROJECT_ID=$(jq -r '.project_info.project_id' "$JSON")
SENDER_ID=$(jq -r '.project_info.project_number' "$JSON")
API_KEY=$(jq -r '.client[0].api_key[0].current_key' "$JSON")
APP_ID=$(jq -r '.client[0].client_info.mobilesdk_app_id' "$JSON")
PACKAGE=$(jq -r '.client[0].client_info.android_client_info.package_name' "$JSON")
WEB_CLIENT_ID=$(jq -r '
  .client[0].oauth_client[]?
  | select(.client_type == 3)
  | .client_id
' "$JSON" 2>/dev/null | head -1)
if [[ -z "$WEB_CLIENT_ID" || "$WEB_CLIENT_ID" == "null" ]]; then
  WEB_CLIENT_ID=""
fi

if [[ -z "$PROJECT_ID" || "$PROJECT_ID" == "null" ]]; then
  echo "generate-firebase-options: project_id okunamadı"
  exit 1
fi

cat >"$OUT" <<DART
// GENERATED by scripts/generate-firebase-options.sh — elle düzenlemeyin.
// Kaynak: mobile/android/app/google-services.json

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

abstract final class FirebaseOptionsGenerated {
  static const bool isConfigured = true;

  static const String projectId = '$PROJECT_ID';
  static const String messagingSenderId = '$SENDER_ID';
  static const String apiKey = '$API_KEY';
  static const String appId = '$APP_ID';
  static const String androidPackageName = '$PACKAGE';
  static const String googleWebClientId = '$WEB_CLIENT_ID';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return const FirebaseOptions(
        apiKey: apiKey,
        appId: appId,
        messagingSenderId: messagingSenderId,
        projectId: projectId,
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return const FirebaseOptions(
          apiKey: apiKey,
          appId: appId,
          messagingSenderId: messagingSenderId,
          projectId: projectId,
        );
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
        return const FirebaseOptions(
          apiKey: apiKey,
          appId: appId,
          messagingSenderId: messagingSenderId,
          projectId: projectId,
          iosBundleId: 'com.mesutbyrm.canlifal',
        );
      default:
        throw UnsupportedError(
          'FirebaseOptionsGenerated: $defaultTargetPlatform desteklenmiyor',
        );
    }
  }
}
DART

echo "✓ $OUT"
