#!/usr/bin/env bash
# Dokümante canlı test hesapları — docs/KULLANICI_TEST_KILAVUZU.md
# Şifreler repoda zaten açık; CI secret'ları hatalı/eksikse güvenli geri dönüş.
set -euo pipefail

DEFAULT_ACCEPTANCE_USER_EMAIL="cursor.test.1786235468@mailinator.com"
DEFAULT_ACCEPTANCE_USER_USERNAME="cursorusr1786235468"
DEFAULT_ACCEPTANCE_USER_PASSWORD="CursorTest!1786235468"
DEFAULT_ACCEPTANCE_HOST_EMAIL="cursor.host.1786235468@mailinator.com"
DEFAULT_ACCEPTANCE_HOST_PASSWORD="CursorTest!1786235468"

# Secret yoksa veya boşsa varsayılanları uygula.
apply_acceptance_credential_defaults() {
  USER_EMAIL="${USER_EMAIL:-${ACCEPTANCE_USER_EMAIL:-$DEFAULT_ACCEPTANCE_USER_EMAIL}}"
  USER_USERNAME="${USER_USERNAME:-${ACCEPTANCE_USER_USERNAME:-$DEFAULT_ACCEPTANCE_USER_USERNAME}}"
  USER_PASSWORD="${USER_PASSWORD:-${ACCEPTANCE_USER_PASSWORD:-$DEFAULT_ACCEPTANCE_USER_PASSWORD}}"
  HOST_EMAIL="${HOST_EMAIL:-${ACCEPTANCE_HOST_EMAIL:-$DEFAULT_ACCEPTANCE_HOST_EMAIL}}"
  HOST_PASSWORD="${HOST_PASSWORD:-${ACCEPTANCE_HOST_PASSWORD:-$DEFAULT_ACCEPTANCE_HOST_PASSWORD}}"
  VIEWER_EMAIL="${VIEWER_EMAIL:-${ACCEPTANCE_VIEWER_EMAIL:-$USER_EMAIL}}"
  VIEWER_PASSWORD="${VIEWER_PASSWORD:-${ACCEPTANCE_VIEWER_PASSWORD:-$USER_PASSWORD}}"
}
