// GENERATED by scripts/generate-firebase-options.sh — elle düzenlemeyin.
// Kaynak: mobile/android/app/google-services.json

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

abstract final class FirebaseOptionsGenerated {
  static const bool isConfigured = true;

  static const String projectId = 'canlifal-android';
  static const String messagingSenderId = '24667749197';
  static const String apiKey = 'AIzaSyD-750KWT8pIvF5P0DdVfDmRCMQM90zssM';
  static const String appId = '1:24667749197:android:e220e714f4c5ff0aae1504';
  static const String androidPackageName = 'com.mesutbyrm.canlifal';
  static const String googleWebClientId = '24667749197-u4d3ep5jdp8lcv4lqg4ngo2ckae4ueh4.apps.googleusercontent.com';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return const FirebaseOptions(
        apiKey: apiKey,
        appId: appId,
        messagingSenderId: messagingSenderId,
        projectId: projectId,
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return const FirebaseOptions(
          apiKey: apiKey,
          appId: appId,
          messagingSenderId: messagingSenderId,
          projectId: projectId,
        );
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
        return const FirebaseOptions(
          apiKey: apiKey,
          appId: appId,
          messagingSenderId: messagingSenderId,
          projectId: projectId,
          iosBundleId: 'com.mesutbyrm.canlifal',
        );
      default:
        throw UnsupportedError(
          'FirebaseOptionsGenerated: ${defaultTargetPlatform} desteklenmiyor',
        );
    }
  }
}
